refactor: simplify the conversion from string to WorkBenchServiceHttp
ava-innersource/Liquid-Application-Framework-1.0-deprecated pull request #137
Opened 2019-12-11 01:57 UTC by guilhermeluizsp

By leveraging the Enum.Parse method, we can remove the manual mapping from string to WorkBenchServiceHttp.

I chose to do the validation inside the setter of the `Name` property because there's no need to convert from `string` to `WorkBenchServiceHttp` everytime we access the `WorkBenchServiceHttp` property.

@bruno-brant The property was previously returning `WorkBenchServiceHttp.GET` in case of conversion failures. Should we keep this behavior?

Closes #132.

2019-12-11 04:15 UTC, bruno-brant commented
I've no idea why it was returning GET for default. 

My take is that this "breaking change" is easy to live with - if there's a runtime out there assigning anything other than a verb to this property, it _should_ throw. Agreed?

2019-12-11 04:32 UTC, bruno-brant requested changes

2019-12-11 04:32 UTC, bruno-brant commented on src/Liquid.Domain/API/StubAPIConfiguration.cs
> +        /// Gets the value of <see cref="Name"/> converted to an <see cref="Liquid.WorkBenchServiceHttp"/>.
Do you know the purpose of this enum? Can you improve the docs?

2019-12-11 04:32 UTC, bruno-brant commented on src/Liquid.Domain/API/StubAPIConfiguration.cs
> +        public string Name
I've checked the code, `Name` doesn't seem to be used a lot. Let's mark it `Obsolete `and tell people to use the enum property which is more safe.

2019-12-11 04:32 UTC, bruno-brant commented on src/Liquid.Domain/API/StubAPIConfiguration.cs
> +                if (!Enum.TryParse(value, ignoreCase: true, result: out workBenchServiceHttp))
Although it certainly makes little difference, two things I would change here:

1. I would omit parameters name, since we are providing a full signature. I don't believe it's usual to do this unless you are calling a method full of defaults.

2. The error you got on CI when you used a _oneliner_ was because of named parameters, so you can go back to the last commit once you've dropped the parameter names.

2019-12-11 04:32 UTC, bruno-brant commented on src/Liquid.Domain/API/StubAPIConfiguration.cs
> +                WorkBenchServiceHttp = workBenchServiceHttp;
If you are obsoleting this property, then, it should be safe to simply remove the backing field _name and just use this as a conversion shortcut for WorkBenchServiceHttp.

2019-12-11 04:34 UTC, bruno-brant commented
One final note: we should remove the whole WorkBenchHttp thing and replace it with the default .NET verb enum, so this will probably disappear as well. 

For now, however, let's leave it at that.

2019-12-16 14:01 UTC, bruno-brant commented
Hey @guilhermeluizsp, do you have an idea when you'll be able to work on this? Do you believe I could do those changes myself on your branch? In any case I want your feedback on those points.

2019-12-16 14:15 UTC, guilhermeluizsp commented
@bruno-brant I'd like to work on this tonight, but I'm completely sure you could finish it yourself.

2019-12-17 01:45 UTC, guilhermeluizsp commented on src/Liquid.Domain/API/StubAPIConfiguration.cs
> +        public string Name
Marked it as obsolete.

2019-12-17 01:51 UTC, guilhermeluizsp commented on src/Liquid.Domain/API/StubAPIConfiguration.cs
> +                if (!Enum.TryParse(value, ignoreCase: true, result: out workBenchServiceHttp))
I like put parameter names when dealing with boolean flags as they usually don't seems to be obvious. I'd rather see `Enum.TryParse(value, ignoreCase: true)` than `Enum.TryParse(value, true)` because, in my opinion, it makes the intent of the code more clearly. But I agree that this is a well known method and explicit parameter names are not so helpful in this case, so I removed anyways.

2019-12-17 01:53 UTC, guilhermeluizsp commented on src/Liquid.Domain/API/StubAPIConfiguration.cs
> +                WorkBenchServiceHttp = workBenchServiceHttp;
I kept the backing field because I chose to keep compatibility with the other property (WorkBenchServiceHttp) to make them reflect into each other. I'd like to have your feedback about this decision.

2019-12-17 01:58 UTC, guilhermeluizsp commented
@bruno-brant As stated in the comments, I marked the `Name` property as obsolete but made it reflect its value into to the `WorkBenchServiceHttp` property (and vice-versa), so that's why I kept the backing field. Do you agree that this was a valid approach?

Since enumerations are integral types at the end of the day, I made sure that those properties only hold valid values, that's why I added those validations.

2019-12-17 02:01 UTC, guilhermeluizsp commented on src/Liquid.Domain/API/StubAPIConfiguration.cs
> +        /// Gets the value of <see cref="Name"/> converted to an <see cref="Liquid.WorkBenchServiceHttp"/>.
I really tried but couldn't come up with a better summary other than "Gets or sets the HTTP method". I'd love to get help from you to improve this.

2019-12-17 11:23 UTC, bruno-brant approved these changes

2019-12-17 11:23 UTC, bruno-brant commented on src/Liquid.Domain/API/StubAPIConfiguration.cs
> +        /// Gets the value of <see cref="Name"/> converted to an <see cref="Liquid.WorkBenchServiceHttp"/>.
I'll make a change, let's see if you like it.

2019-12-17 11:23 UTC, bruno-brant commented on src/Liquid.Domain/API/StubAPIConfiguration.cs
> +                if (!Enum.TryParse(value, ignoreCase: true, result: out workBenchServiceHttp))
Well, I'd have to think on it. `true` really feels like a magic flag here and I always have to check what it means. You may be right!

2019-12-17 11:23 UTC, bruno-brant commented on src/Liquid.Domain/API/StubAPIConfiguration.cs
> +                WorkBenchServiceHttp = workBenchServiceHttp;
Well, we end up having two fields with equivalent values. I'd keep just one of then (the enum preferably) and make the other a _façade_ of sorts, just a shortcut. 

But this is nitpicking on my part; it doesn't make any significant difference. Name is obsolete and we'll remove it as soon as possible.

2019-12-17 11:23 UTC, bruno-brant commented on src/Liquid.Domain/API/StubAPIConfiguration.cs
> +        /// Gets the value of <see cref="Name"/> converted to an <see cref="Liquid.WorkBenchServiceHttp"/>.
Oh.... for some reason I'm seeing the old version of the source in this review window! You've updated it to Get or set.... that's good! I'm marking it as resolved.

2019-12-17 11:23 UTC, merged